### ISSUE TITLE
[ENH] Add support for multistaged Dockerfiles

### ISSUE THREAD

**Issue by paoloantinori** [projectatomic/buildah#242] opened 2017-08-12 13:46 UTC
https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by ripcurld0** [comment] 2018-01-01 17:40
@rhatdan @TomSweeneyRedHat should we support this in `buildah bud`?

**Comment by rhatdan** [comment] 2018-01-02 13:11
Yes, we plan to add this feature in the future.
@nalind Correct?

**Comment by nalind** [comment] 2018-01-02 16:39
@rhatdan Yup.  It'll take some work in the imagebuilder library, which we use to "drive" the bud command, first.

**Comment by TomSweeneyRedHat** [comment] 2018-02-09 20:14
Closing as this is a duplicate of #440.

**Closed by TomSweeneyRedHat** 2018-02-09 20:14 UTC
