### ISSUE TITLE
Permission denied on /var/run/containers/storage

### ISSUE THREAD

**Issue by bkircher** [projectatomic/buildah#420] opened 2018-01-28 10:54 UTC
**Description**

Installing buildah on F27 and executing it for the first time gives a "permission denied".

```
$ buildah from scratch
mkdir /var/run/containers/storage: permission denied
mkdir /var/run/containers/storage: permission denied
exit 1
```

**Steps to reproduce the issue:**
1. Install buildah on a vanilla Fedora 27
2. Run `buildah from scratch`

**Output of `rpm -q buildah` or `apt list buildah`:**

```
$ rpm -qa|grep buildah 
buildah-0.11-1.git6bad262.fc27.x86_64
```

**Output of `buildah version`:**

```
$ buildah --version
buildah version 0.11 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `cat /etc/*release`:**

```
$ cat /etc/os-release 
NAME=Fedora
VERSION="27 (Twenty Seven)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Twenty Seven)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```

**Output of `uname -a`:**

```
$ uname -a
Linux ikki 4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
$ cat /etc/containers/storage.conf 
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

```

**Comment by rhatdan** [comment] 2018-01-28 14:58
You have to be root to run buildah.

**Comment by ripcurld0** [comment] 2018-01-28 15:01
@rhatdan can't we create a `buildah` group that allows non-root users to run buildah w/o `sudo`-ing (something similar to what `docker` does)?

**Comment by rhatdan** [comment] 2018-01-28 17:29
No there is no client server operation for that.  A better way is to just to setup sudo for the buildah command it would be more secure then doing the docker group thing.

**Comment by bkircher** [comment] 2018-01-28 18:00
> You have to be root to run buildah.

I've already imagined something like that. I could create a PR that adds a notice to the man page or the README. Would that be alright?

**Comment by ripcurld0** [comment] 2018-01-28 18:09
@bkircher that would be super!

**Comment by rhatdan** [comment] 2018-02-12 15:41
Closing this issue.

**Closed by rhatdan** 2018-02-12 15:41 UTC
Labels: docs, help wanted

**Comment by kris-nova** [comment] 2018-10-18 19:39
Also was just hit by this - as a user, it would have saved me a *lot* of time if the program would have just checked how it was being executed at runtime and exited if it was being ran as a non root user with a meaningful exit code and message.

Happy to PR that if you agree.

**Comment by TomSweeneyRedHat** [comment] 2018-10-18 20:03
@rhatdan thoughts?  You can run Buildah as non-root these days we haven't gotten it well documented yet and we're working on that.  A good error message sounds good to me and I'm never against a PR.

**Comment by rhatdan** [comment] 2018-10-19 12:53
@kris-nova Please submit a PR.  @giuseppe Can we make this smarter like Podman and just do the right thing if when run as non-root

**Comment by giuseppe** [comment] 2018-10-22 10:38
this should not happen, I'll look into it.  @kris-nova what version of buildah are you using?

**Comment by giuseppe** [comment] 2018-10-22 11:43
this should not happen, I'll look into it.  @kris-nova what version of buildah are you using?

**Comment by giuseppe** [comment] 2018-10-22 15:51
@kris-nova great presentation on TGI Kubernetes 054!  I think it might be something related to Ubuntu, as we probably never tried rootless there :-)  I'll try that

**Comment by giuseppe** [comment] 2018-10-22 16:07
I had to install an updated runc and I got it running on Ubuntu 18.10

**Comment by SveWoCo** [comment] 2019-04-10 08:07
Hi, I'm facing the same issue on an Ubuntu 16.04 wih runc version 1.0.1-rc6 and buildah 1.8-dev. 
Are there some more Informations on this? It was working just until yesterday for me. What version of runc did you update to?

**Comment by giuseppe** [comment] 2019-04-10 08:24
> Hi, I'm facing the same issue on an Ubuntu 16.04 wih runc version 1.0.1-rc6 and buildah 1.8-dev.
> Are there some more Informations on this? It was working just until yesterday for me. What version of runc did you update to?

is it caused by an updated runc or have you also updated buildah?

**Comment by SveWoCo** [comment] 2019-04-10 08:36
I use the Packages provided by the project atomic PPA. And according to /var/log/dpkg.log, the last update was for buildah. It made a jump from 1.6.1 to 1.8.1.
Runc was not touched as it seems.

**Comment by SveWoCo** [comment] 2019-04-11 08:24
Ok I manually build release 1.6, 1.7, 1.7.1 and 1.7.2. The problem appears starting with 1.7.2. The releases prior to 1.7.2 are working fine.

**Comment by giuseppe** [comment] 2019-04-11 08:39
have you also tried last version from master?

**Comment by SveWoCo** [comment] 2019-04-11 08:45
Yes, I just tried it. Same problem. as in 1.7.2.

**Comment by giuseppe** [comment] 2019-04-11 08:55
thanks for trying it, I am going to reproduce here.  What commands have you used?

**Comment by SveWoCo** [comment] 2019-04-11 08:58
Basically just buildah version, buildah containers and buildah images.

**Comment by giuseppe** [comment] 2019-04-11 09:30
I cannot see this issue locally, can you show the content of `~/.config/containers/storage.conf`?

**Comment by SveWoCo** [comment] 2019-04-11 09:33
Of course, it contains only:
`RunRoot = "/run/user/500071028"
GraphRoot = "/home/uidg8755/.local/share/containers/storage"
GraphDriverName = "vfs"
`

**Comment by giuseppe** [comment] 2019-04-11 09:37
it looks like a config file generated by an old (and broken) version of libpod.  Could you delete `~/config/containers` and try again?

**Comment by SveWoCo** [comment] 2019-04-11 09:41
Ah, ok. That did the trick. The storage.conf also has gotten a few more entries. Thank you!

**Comment by giuseppe** [comment] 2019-04-11 09:49
good to hear!  You most likely also got fuse-overlayfs storage configured

**Comment by SveWoCo** [comment] 2019-04-11 10:08
According to storage.conf vfs should be used. 

> [storage]
  driver = "vfs"
  runroot = "/tmp/500071028"
  graphroot = "/home/uidg8755/.local/share/containers/storage"
  [storage.options]
    size = ""
    remap-uids = ""
    remap-gids = ""
    remap-user = ""
    remap-group = ""
    ostree_repo = ""
    skip_mount_home = ""
    mount_program = ""
    mountopt = ""
    [storage.options.thinpool]
      autoextend_percent = ""
      autoextend_threshold = ""
      basesize = ""
      blocksize = ""
      directlvm_device = ""
      directlvm_device_force = ""
      fs = ""
      log_level = ""
      min_free_space = ""
      mkfsarg = ""
      mountopt = ""
      use_deferred_deletion = ""
      use_deferred_removal = ""
      xfs_nospace_max_retries = ""

Is there anything missing? 
_buildah mount_ tells me: 
>chown /home/uidg8755/.local/share/containers/storage/vfs: operation not permitted

**Comment by rhatdan** [comment] 2019-04-11 11:55
In rootless mode 
buildah mount should be done in a `buildah umount`

**Comment by SveWoCo** [comment] 2019-04-11 12:04
Ok I don't really understand that answer. I'm trying to mount the filesystem of a container, that was created with `buildah from xyz`. For this I'm trying `buildah mount xyz-working-container`. 
Together with the debug option I'm getting this:

> DEBU[0000] [graphdriver] trying provided driver "vfs"   
chown /home/uidg8755/.local/share/containers/storage/vfs: operation not permitted

Therefore the question if I'm missing some option in the storage.conf or if there is something completely off on my side.

**Comment by andrew-aladev** [comment] 2019-12-28 09:22
```
buildah unshare -- sh -c "buildah mount 4b258341e17c"
```

`4b258341e17c` - this is my container, works fine.
