### ISSUE TITLE
repoquery (dnf-utils) denied by selinux in buildah container

### ISSUE THREAD

**Issue by carlwgeorge** [projectatomic/buildah#482] opened 2018-02-17 03:14 UTC
**Description**

I want to create a minimal repoquery container from scratch, but it doesn't work with SELinux enforcing.

**Steps to reproduce the issue:**
1. `ctr=$(buildah from scratch)`
2. `mnt=$(buildah mount $ctr)`
3. `dnf install --installroot $mnt --release 27 dnf-utils --setopt install_weak_deps=false`
4. `buildah run $ctr -- repoquery --whatprovides webserver`

**Describe the results you received:**

```
Can not read configuration: /etc/dnf/dnf.conf , ignoring
Config error: Permission denied: '/var/log/dnf.log'
```

**Describe the results you expected:**

```
Last metadata expiration check: 1:05:43 ago on Sat Feb 17 01:52:48 2018.
caddy-0:0.10.10-1.fc27.x86_64
cherokee-0:1.2.104-1.fc25.i686
cherokee-0:1.2.104-1.fc25.x86_64
cherokee-0:1.2.104-6.fc27.i686
cherokee-0:1.2.104-6.fc27.x86_64
httpd-0:2.4.28-1.fc27.x86_64
httpd-0:2.4.29-1.fc27.x86_64
lighttpd-0:1.4.45-5.fc27.x86_64
lighttpd-0:1.4.48-1.fc27.x86_64
nginx-1:1.12.1-1.fc27.x86_64
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.12-1.git8badcc2.fc27.x86_64
```

**Output of `buildah version`:**

```
Version:       0.12
Go Version:    go1.9.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    8badcc2
Built:         Mon Feb 12 13:03:52 2018
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME=Fedora
VERSION="27 (Twenty Seven)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Twenty Seven)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```

**Output of `uname -a`:**

```
Linux zeratul 4.15.3-300.fc27.x86_64 #1 SMP Tue Feb 13 17:02:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Additional info:**

The error seems similar to #337, but that issue was closed and appeared to be resolved in 0.8.

**Comment by rhatdan** [comment] 2018-02-19 13:49
Please attach the AVC messages you are seeing?

**Comment by rhatdan** [comment] 2018-02-19 14:00
@nalind There seems to be a big difference between the way we handle `buildah from scratch` from how we handle `buildah from fedora`?

We don't see to be mounting an overlay which would set the SELinux label, for scratch.  Since this is not an overlay mount, the dnf tol is putting down real labels in the container image, and when you finally run a container on the image, it gets permission denied.  If we do buildah from fedora, the overlay causes the image to be mounted with a single label and all the content gets created with that label, and everything works well.

**Comment by carlwgeorge** [comment] 2018-02-19 14:42
```
type=AVC msg=audit(1519051255.093:268): avc:  denied  { read } for  pid=4781 comm="repoquery" name="openssl.cnf" dev="sda2" ino=1190215 scontext=system_u:system_r:container_t:s0:c208,c551 tcontext=system_u:object_r:cert_t:s0 tclass=file permissive=0
type=AVC msg=audit(1519051255.156:269): avc:  denied  { write } for  pid=4781 comm="repoquery" name="tmp" dev="sda2" ino=1184854 scontext=system_u:system_r:container_t:s0:c208,c551 tcontext=system_u:object_r:tmp_t:s0 tclass=dir permissive=0
type=AVC msg=audit(1519051255.156:270): avc:  denied  { write } for  pid=4781 comm="repoquery" name="tmp" dev="sda2" ino=1186339 scontext=system_u:system_r:container_t:s0:c208,c551 tcontext=system_u:object_r:tmp_t:s0 tclass=dir permissive=0
type=AVC msg=audit(1519051255.156:271): avc:  denied  { write } for  pid=4781 comm="repoquery" name="tmp" dev="sda2" ino=1186339 scontext=system_u:system_r:container_t:s0:c208,c551 tcontext=system_u:object_r:tmp_t:s0 tclass=dir permissive=0
type=AVC msg=audit(1519051255.156:272): avc:  denied  { write } for  pid=4781 comm="repoquery" name="diff" dev="sda2" ino=1184198 scontext=system_u:system_r:container_t:s0:c208,c551 tcontext=system_u:object_r:root_t:s0 tclass=dir permissive=0
type=AVC msg=audit(1519051255.157:273): avc:  denied  { write } for  pid=4781 comm="repoquery" name=".dbenv.lock" dev="sda2" ino=1184224 scontext=system_u:system_r:container_t:s0:c208,c551 tcontext=unconfined_u:object_r:container_share_t:s0 tclass=file permissive=0
type=AVC msg=audit(1519051255.157:274): avc:  denied  { append } for  pid=4781 comm="repoquery" name="dnf.log" dev="sda2" ino=1184216 scontext=system_u:system_r:container_t:s0:c208,c551 tcontext=unconfined_u:object_r:container_share_t:s0 tclass=file permissive=0
```

**Comment by rhatdan** [comment] 2018-02-19 16:56
@carlwgeorge Thanks, we figured out what the issue is, and @nalind is looking into a fix.

**Comment by rhatdan** [comment] 2018-02-22 13:56
Since 
https://github.com/projectatomic/buildah/pull/486
has merged this should be fixed.  I will build a new version of buildah for Fedora and RHEL.

**Closed by rhatdan** 2018-02-22 13:56 UTC

**Comment by carlwgeorge** [comment] 2018-02-22 15:22
Thanks Dan!
