### ISSUE TITLE
buildah bud doesn't like RUN with `&&`

### ISSUE THREAD

**Issue by ipbabble** [projectatomic/buildah#695] opened 2018-05-15 19:35 UTC
**Description**

When using buildah bud with a Dockerfile that contains a RUN with  `&&` , the build fails on the `&&` 

**Steps to reproduce the issue:**
1.  Use the following Dockerfile
```
# Base on the Fedora
FROM docker://docker.io/fedora:latest
MAINTAINER http://fedoraproject.org/wiki/Cloud
RUN dnf -y update && dnf clean all
RUN dnf -y install nginx && dnf clean all
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN echo "nginx on Fedora" > /usr/share/nginx/html/index.html
EXPOSE 80
CMD [ "/usr/sbin/nginx" ]
```
2. Use `buildah bud .`

**Describe the results you received:**

Error: Transaction failed
error building: error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTTAG=f28container FGC=f28 FBR=f28] Command:run Args:[dnf -y update && dnf -y clean all] Flags:[] Attrs:map[] Message:RUN dnf -y update && dnf -y clean all Original:RUN dnf -y update && dnf -y clean all}: exit status 1

**Describe the results you expected:**

Successful build.

Changing `&&` to `;` makes this work. But some people us `&&`.

So
```
RUN dnf -y update; dnf clean all
RUN dnf -y install nginx; dnf clean all
```
... works

**Output of `rpm -q buildah` or `apt list buildah`:**

```
# rpm -q buildah 
buildah-0.16-1.git82529cd.fc28.x86_64
```

**Output of `buildah version`:**

```
# buildah -v
buildah version 0.15 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `cat /etc/*release`:**

```
Fedora release 28 (Twenty Eight)
```

**Output of `uname -a`:**

```
Linux jappa.cos.redhat.com 4.16.8-300.fc28.x86_64 #1 SMP Wed May 9 20:23:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

```

**Comment by pixdrift** [comment] 2018-05-16 12:52
Can't reproduce on `buildah 1.0 ce8d467`, have tested the `dnf` example above, and the following simplified Dockerfile:
```
FROM docker://docker.io/fedora:latest
RUN echo before && echo after
```

```
# buildah bud andand
STEP 1: FROM docker://docker.io/fedora:latest
STEP 2: RUN echo before && echo after
before
after
STEP 3: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]@ca5530463093575ed7540be7e6dcc6ecbd8ed68a1682b9d7a19832ee8fcb2754
Getting image source signatures
Skipping fetch of repeat blob sha256:891e1e4ef82ad02a4ea1f030831f942d722c7694c4db64ca3239c8163b811c58
Copying blob sha256:0130e552a712c9e855452bd379833215d41f15b6c1f83301d17bbf13f69f0f35
 113 B / 113 B [============================================================] 0s
Copying config sha256:64d6db105c0a730c750464c0d0c1b52a0783cadd6a618257c64434a747d9133d
 1.45 KiB / 1.45 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
ca5530463093575ed7540be7e6dcc6ecbd8ed68a1682b9d7a19832ee8fcb2754
```

**Comment by rhatdan** [comment] 2018-05-16 13:01
@ipbabble Could you verify this is fixed in 1.0?
@ipbabble @pixdrift Could you guys update karma on buildah 1.0 so we can get it out of testing.

**Comment by pixdrift** [comment] 2018-05-16 13:06
@rhatdan, are you referring to the release v1.0 (1ab80bc)? or you after a second data point to confirm?

I can install 1.0 release quickly and re-test if that is sufficient.

**Comment by rhatdan** [comment] 2018-05-16 13:29
Yes @pixdrift I just want @ipbabble to say he confirms it and there is not something system specific going on.

**Closed** 2018-05-16 16:10 UTC
