### ISSUE TITLE
ostree is not supported on Centos

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#479] opened 2018-02-14 05:05 UTC
```
# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)

# buildah version
Version:       0.12
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    e073df1
Built:         Wed Feb 14 04:40:44 2018
OS/Arch:       linux/amd64

# buildah --debug push docker.io/busybox:latest ostree:busybox:latest
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: override_kernelcheck=true           
DEBU[0000] overlay test mount with multiple lowers succeeded 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false   
ERRO[0000] The transport "ostree:" is not supported in this build 
```

**Comment by rhatdan** [comment] 2018-02-14 10:45
Does this cause an issue, or are you just showing that it is not supported?

**Comment by gouyang** [comment] 2018-02-14 11:17
just showing it's not supported

**Comment by ripcurld0** [comment] 2018-02-14 11:23
@rhatdan is this a bug?
IMHO it's an expected behavior. Not all machines have support to `ostree`.

**Comment by rhatdan** [comment] 2018-02-14 11:58
Although I think this is just a compiler issue, we did not build buildah with ostree support.  But ostree is not that important to buildah since it would only come into play if  you wanted to buildah push to an ostree pool.  You could still use skopeo to move the content out of container/storage into ostree.

**Comment by ripcurld0** [comment] 2018-02-14 12:05
Thanks. I guess we can close it then.

**Closed by ripcurld0** 2018-02-14 12:05 UTC

**Comment by rhatdan** [comment] 2018-02-15 16:53
Does this cause an issue, or are you just showing that it is not supported?
