### ISSUE TITLE
buildah from image create unexpected container name

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#396] opened 2018-01-17 00:13 UTC
It should create container name `busybox2-working-container` rather than the name `busybox-working-container-4`.

```
[root@fedora buildah]# buildah from busybox2
busybox-working-container-4
```

**Comment by ripcurld0** [comment] 2018-01-17 07:18
Hi @gouyang 
I tried to reproduce it but unsuccessfully.

Here are my steps:
```sh
$ sudo ./buildah from --name bla docker://busybox
bla
$ sudo ./buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
cf1f5f6da075     *     6ad733544a63 docker.io/library/busybox:latest bla
$ sudo ./buildah commit bla busybox2
$ sudo ./buildah images
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
6ad733544a63         docker.io/library/busybox:latest                         Nov 3, 2017 22:39      1.278 MB
c8451f3f397e         docker.io/library/busybox2:latest                        Jan 17, 2018 06:58     1.278 MB
$ sudo ./buildah from docker://busybox2
busybox2-working-container
```

Can you describe your steps, please?

Thanks.

**Comment by gouyang** [comment] 2018-01-17 23:51
It works for the committed images, which I don't cover in the test, I will add a test for it.
It fails for the tagged images, steps like below. The problem happens recently as it works before, it works on buildah-0.9.

```
[root@fedora buildah]# ./buildah from busybox
busybox-working-container
[root@fedora buildah]# ./buildah tag busybox busybox2
[root@fedora buildah]# ./buildah from busybox2
busybox-working-container-2

[root@fedora buildah]# ./buildah commit busybox-working-container busybox3
[root@fedora buildah]# ./buildah from busybox3
busybox3-working-container
```

**Comment by TomSweeneyRedHat** [comment] 2018-01-18 00:19
@gouyang tyvm for the reproducer!

**Comment by ripcurld0** [comment] 2018-01-18 10:39
It looks like when running `buildah commit` the image gets a new image ID while tag keeps the same image ID. When `buildah from` is being executed it generates the name from `FromImage` in the `Builder` structure.

If the image is a tag then the `FromImage` will contain the original image. Otherwise, it will be the name given in `buildah commit`.

I think I can work on this, if you don't mind.

**Comment by rhatdan** [comment] 2018-01-18 12:09
GO for it.

**Comment by gouyang** [comment] 2018-01-27 01:38
There is still an problem I met:
1. it works
```
# buildah tag busybox busybox1
# buildah from busybox1
busybox1-working-container-4
```
2. not work
```
# buildah from docker.io/busybox1
busybox-working-container-4
```
3. it works
```
# buildah from docker.io/library/busybox1
busybox1-working-container-5
```

**Comment by TomSweeneyRedHat** [comment] 2018-01-27 15:59
@gouyang thanks for the update and interesting development.  @ripcurld0 can you take a peak?

**Comment by ripcurld0** [comment] 2018-01-27 16:06
@gouyang when I do `docker.io/busybox1` I get
```
no such image "docker.io/busybox1": image not known
```

The same thing with `docker.io/library/busybox1`.
Which means I can't reproduce this problem. Can you show the entire flow?

Thanks.

**Comment by ripcurld0** [comment] 2018-02-04 12:53
@gouyang would you mind test this issue again. 
Commit id: https://github.com/projectatomic/buildah/commit/815cedfc71fff7460b683b5f9e8fe053b31a31ef
PR: https://github.com/projectatomic/buildah/pull/422

Let me know if you find anything new. Till then, I am closing this issue.

Thanks.

**Closed by ripcurld0** 2018-02-04 12:53 UTC
Labels: bug
