### ISSUE TITLE
add/copy --chown cannot determine username

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#416] opened 2018-01-26 07:43 UTC
1. add/copy --chown can work with uid

```
# grep buildah /etc/passwd
buildah:x:1001:1001:Test buildah:/home/buildah:/bin/bash

# buildah add --chown 1001:1001 nginxc auth.json 
```
2. add/copy --chown fail to determine username, the user `buildah` is existing.
```
# buildah add --chown buildah nginxc auth.json 
error adding content to container "nginxc": error determining run uid: user: unknown user error looking up user "buildah"
# buildah add --chown buildah:buildah nginxc auth.json 
error adding content to container "nginxc": error determining run uid: user: unknown user error looking up user "buildah"
```

**Comment by rhatdan** [comment] 2018-01-27 08:51
The buildah user needs to be defined inside of the container image.  It is not looking at the hosts /etc/passwd, attempt the same tests with "bin" rather then buildah and it will work, because bin is defined inside the container image /etc/passwd.

**Comment by gouyang** [comment] 2018-01-29 01:09
The uid 1001 is not in the image's /etc/passwd as well, why it can work?

**Comment by rhatdan** [comment] 2018-01-29 06:23
If the USERNAME is a Int, it will not attempt to look for the content in the /etc/passwd file in the container but will just use the UID.  The problem is when using a non UID, the container runtime needs to translate the UserName into a UID via the /etc/passwd in the container.  This works the same way on Docker.

**Comment by ripcurld0** [comment] 2018-01-29 09:04
@rhatdan from what I understand this is not a bug but an expected behavior.
Can we close it?

**Comment by rhatdan** [comment] 2018-01-29 11:42
Yes. @gouyang Reopen if you disagree.

**Closed by rhatdan** 2018-01-29 11:42 UTC
Labels: bug

**Comment by oblitum** [comment] 2019-08-20 15:42
Hey folks, I got some similar issue:

```
RUN groupadd -g 1000 francisco \
 && useradd -g francisco -G wheel -u 1000 -ms /bin/zsh francisco \
 && sed -i -e 's/^# %wheel ALL=(ALL) NOPASSWD: ALL$/%wheel ALL=(ALL) NOPASSWD: ALL/' /etc/sudoers

RUN su francisco -c "git clone --depth 1 https://aur.archlinux.org/yay.git /tmp/yay && cd /tmp/yay && makepkg -cs" \
 && cd /tmp/yay && pacman -U --noconfirm *.pkg.tar.xz && cd .. && rm -rf yay

USER francisco
WORKDIR /home/francisco

COPY --chown=francisco:francisco dotfiles .
```

I got this error when I tried to build the image with `--squash`:

```
STEP 7: COPY --chown=francisco:francisco dotfiles .
Error: error building at STEP "COPY --chown=francisco:francisco dotfiles .": error determining run uid: user: unknown user error looking up user "francisco"
```

I've build my `Dockerfile` previously without `--squash` and it worked.
