### ISSUE TITLE
The output of pulling image is redirecting to stderr

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#666] opened 2018-05-08 08:36 UTC
I think all outputs should go to stdout, but some go to stderr, is it by design?
```
[root@dhcp-136-62 ~]# cat test.sh 
#!/bin/bash
exec 1> ./test.stdout
exec 2> ./test.stderr
buildah from busybox
[root@dhcp-136-62 ~]# bash test.sh
[root@dhcp-136-62 ~]# cat test.stdout 
busybox-working-container
[root@dhcp-136-62 ~]# cat test.stderr 
Getting image source signatures
Copying blob sha256:f70adabe43c0cccffbae8785406d490e26855b8748fc982d14bc2b20c778b929
 706.22 KiB / 706.22 KiB [==================================================] 1s
Copying config sha256:8ac48589692a53a9b8c2d1ceaa6b402665aa7fe667ba51ccc03002300856d8c7
 1.46 KiB / 1.46 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
```

**Comment by ripcurld** [comment] 2018-05-08 08:37
No, it's not supposed to do that.

**Comment by ripcurld** [comment] 2018-05-08 08:56
@rhatdan it seems like we are using `os.Stderr` as `ReportWriter` which prints all the progress into stderr. Was there a reason for that?

**Comment by rhatdan** [comment] 2018-05-08 12:44
I think this is for scripting.

ctr=$(buildah pull fedora)
You don't want $ctr to have all of the pull information in it.

**Comment by ripcurld** [comment] 2018-05-08 13:07
Well, I am a little bit torn here.
*Docker* prints to `stdout`, while *wget* and *curl* redirecting the progress to `stderr`.
I am not sure what is the right thing to do here but knowing this made me think this is not as bad as I thought.

WDYT?

**Comment by rhatdan** [comment] 2018-05-10 13:40
I think buildah is going the correct thing for the redirection of the container name.  So I am going to close this issue as not a bug.

**Closed by rhatdan** 2018-05-10 13:40 UTC
