### ISSUE TITLE
Buildah RPM spec missing Requires for ostree

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#432] opened 2018-01-30 23:07 UTC
The buildah RPM  spec used to build RPM in CentOS extras is missing the `Requires` for the ostree package which provides libostree-1.so.1.

**Description**

After installing buildah RPM for CentOS extras buildah fails to run, producing the following error:

`buildah: error while loading shared libraries: libostree-1.so.1: cannot open shared object file: No such file or directory`

**Steps to reproduce the issue:**
1. Add required repos to yum configuration
2. `yum install buildah`
3. execute `buildah`

**Describe the results you received:**
`buildah: error while loading shared libraries: libostree-1.so.1: cannot open shared object file: No such file or directory`

**Describe the results you expected:**
All libraries required for buildah to be defined in RPM and installed in yum install step.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.9-1.git04ea079.el7.x86_64
```

**Output of `buildah -v`:**

```
buildah version 0.9 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Workaround:**
Manually install ostree package to resolve missing library/dependency issue
1. `yum install ostree`

**Comment by rhatdan** [comment] 2018-01-31 04:50
@lsm5 PTAL

**Comment by ripcurld0** [comment] 2018-02-05 14:06
@pixdrift thank you for fixing this issue. I am closing this as #434 was merged.

**Comment by lsm5** [comment] 2018-02-05 14:50
@pixdrift btw, what's the yum repo you're getting the rpm from?

**Comment by pixdrift** [comment] 2018-02-05 20:51
@lsm5 I am getting it from CentOS
http://mirror.centos.org/centos/7/extras/x86_64/Packages/

But they don't appear to using the spec file from contrib.

**Comment by pixdrift** [comment] 2018-02-05 20:52
@ripcurld0 it wasn't merged.

**Comment by lsm5** [comment] 2018-02-05 20:55
yup, `contrib/` is just a reference thing. And not the canonical rpm source. And the `mirror.centos.org` tells me it was inherited from RHEL. Would you mind filing a bug on Red Hat Bugzilla against the 'buildah' component? Let me know if any issues.

@rhatdan please remind me if ostree dep is needed in Ubuntu as well?

**Comment by pixdrift** [comment] 2018-02-05 20:56
Which Red Hat repo is this being pushed to? I would prefer to use the Red Hat source.

**Comment by lsm5** [comment] 2018-02-05 20:58
@pixdrift well, you'd need to be a RHEL customer to use RHEL yum repos, but anyway, I'll take care of the bugfiling and fixing, no worries.

**Comment by pixdrift** [comment] 2018-02-05 21:03
@lsm5, appreciate it. To be honest, wasn't expecting to see it in the RHEL repos this early.

Can I get the Red Hat Bugzilla # off you so I can track progress?

Cheers.

**Comment by lsm5** [comment] 2018-02-05 21:09
If you don't mind using CentOS Virtualization SIG repos, might wanna try the yum repo in here: https://wiki.centos.org/Container/Tools .. this usually has packages rebuilt from fedora rawhide, and thus often ahead of RHEL. Use this if you don't mind your system being *quite different from RHEL/base CentOS*. Haven't fixed this issue in there yet, but I'll take care of it in a bit

**Comment by pixdrift** [comment] 2018-02-05 21:09
@lsm5 as per this discussion the `runc Requires` minimum version in the spec also needs to be bumped to the newer rc4 version available in the repo which can probably be fixed at the same time:
[https://github.com/projectatomic/buildah/issues/435](url)

**Comment by lsm5** [comment] 2018-02-05 21:10
by *quite different* I mean that I take the liberty to bump up dependencies in the base system if docker or other packages need newer deps

**Comment by ripcurld0** [comment] 2018-02-05 21:11
@pixdrift my bad. I am terribly sorry. I am going to reopen it, till the problem is solved.

**Comment by pixdrift** [comment] 2018-02-05 21:14
@lsm5 appreciate the potential impact of running from Rawhide, which is why I choose RHEL/CentOS/EPEL/OL sources. As you mentioned above, the contrib version of the spec _isn't_ the canonical source.. but where is for the RHEL package?

These packages aren't in the primary OS channels so what is the RHEL process for pulling RPMs into extras?

Is there a location where the upstream RPM .specs that Red Hat consumes live that I can raise bugs against directly?

**Comment by lsm5** [comment] 2018-02-05 21:18
@pixdrift well, RHEL sources are available in the wild _only_ in the form of srpms AFAIK. But since we know that the bug you see is from base CentOS, it's most certainly a RHEL bug, since CentOS base and Extras gotta ensure compatibility with RHEL. And the way to raise bugs against RHEL rpms is to file a bug on `bugzilla.redhat.com`, or you could just file a CentOS bug on `bugs.centos.org`. Hope that helps.

**Comment by pixdrift** [comment] 2018-02-05 21:26
@lsm5 the Virtualization sig repo you linked to appears to have much _older_ buildah version. (0.5)
[https://cbs.centos.org/repos/virt7-container-common-candidate/x86_64/os/Packages/]()

I will stick with RHEL and raise with RHEL bugzilla in the future, as mentioned above, didn't realise these packages where in RHEL repos so early (alpha/rc4). Still keen to update the contrib in this repo as I will build from here until RHEL official catches up.

**Comment by lsm5** [comment] 2018-02-05 21:31
ha, guess I haven't bumped it in a bit

**Comment by pixdrift** [comment] 2018-02-05 21:35
Is there a facility to setup nightlies?

**Comment by rhatdan** [comment] 2018-02-05 21:39
No we should compile buildah on Ubuntu with the ostree stuff compiled out.

**Comment by rhatdan** [comment] 2018-03-17 22:55
The rpm figures out that buildah needs the library which will cause it to be installed.

```
rpm -q buildah --requires | grep libostree
libostree-1.so.1()(64bit)
libostree-1.so.1(LIBOSTREE_2016.3)(64bit)
libostree-1.so.1(LIBOSTREE_2016.8)(64bit)
```

**Comment by pixdrift** [comment] 2018-04-04 09:28
Can I get this re-opened.. there is an outstanding issue when building for EL7.

The spec file in contrib lists 'ostree-libs' in the `Requires` but the package isn't split in EL7, and the required libraries are in the `ostree` package.

Can the spec file in contrib be updated to require the library rather than the package so the same spec file works across EL7/Fedora? Alternatively, an if block can be added to change the requires based on OS version.

This is a fresh rpmbuild from `master` using the spec file from contrib
```
Error: Package: buildah-0.15.1-1.git5ce8009.el7.x86_64 (/buildah-0.15.1-1.git5ce8009.el7.x86_64)
           Requires: ostree-libs
```

Requires line is here:
https://github.com/projectatomic/buildah/blob/master/contrib/rpm/buildah.spec#L52

I appreciate (as mentioned above) this isn't the canonical source for the spec, but it's the most reliable (public) spec I have to work from.

**Comment by ripcurld** [comment] 2018-04-04 13:10
@pixdrift #551 was merged. before closing this issue, do you mind testing?
Thanks.

**Comment by pixdrift** [comment] 2018-04-04 13:16
@ripcurld build with updated spec is all good 👍, tested on CentOS 7. I do my best not to resurrect this issue for a third time.  😃

**Comment by ripcurld** [comment] 2018-04-04 13:30
@pixdrift thank you very much. I am closing this but feel free to re-open it or continue the conversation.

**Closed by ripcurld** 2018-04-04 13:30 UTC
