### ISSUE TITLE
buildah export can not export to STDOUT

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#224] opened 2017-07-27 09:45 UTC
```  
[root@fedora tmp]# buildah export  -h
NAME:
   buildah export - Export container's filesystem contents as a tar archive

USAGE:
   buildah export [command options] CONTAINER

DESCRIPTION:
   This command exports the full or shortened container ID or container name to
   STDOUT and should be redirected to a tar file.
       

OPTIONS:
   --output value, -o value  write to a file, instead of STDOUT
   
[root@fedora tmp]# buildah export  nginx-working-container-5
ERRO[0000] Refusing to save to a terminal. Use the -o flag or redirect. 
```

**Comment by rhatdan** [comment] 2017-07-27 10:38
This is by design, matches docker export
buildah export nginx-working-container-5 > /tmp/nginx.tar

Should work.  BTW I am thinking of removing export support and leaving this to kpod.  I dropped the patch set to add kpod import.

**Comment by gouyang** [comment] 2017-07-27 22:55
Understanding it now. Should I close the issue or leave it to you decision is making.

**Comment by rhatdan** [comment] 2017-07-28 11:59
Yes I can close it.

**Closed by rhatdan** 2017-07-28 11:59 UTC
