### ISSUE TITLE
error messsage not useful when image not found on RHEL

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#474] opened 2018-02-13 08:05 UTC
```
# buildah from busybox
unknown: Not Found

# buildah version
Version:       0.12
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    e073df1
Built:         Tue Feb 13 15:51:59 2018
OS/Arch:       linux/amd64
```

**Comment by ripcurld0** [comment] 2018-02-13 12:33
@gouyang can't reproduce it.

**Comment by gouyang** [comment] 2018-02-13 13:15
@ripcurld0 are you reproducing it on RHEL?

**Comment by ripcurld0** [comment] 2018-02-13 13:24
No, `Fedora 27`

**Comment by gouyang** [comment] 2018-02-13 23:51
The issue s reported on RHEL, it cannot see this error on Fedora.

**Comment by gouyang** [comment] 2018-02-14 04:56
It's not happened on `centos`.  it happened on RHEL because of it only search `registry.access.redhat.com` by default. 

```
# cat /etc/containers/registries.conf 
....
[registries.search]
registries = ['registry.access.redhat.com']
```

If add `docker.io` to the registries.search or remove `registry.access.redhat.com`, the image can be pulled and no error occurs. 

The issue is complaining the error message `unknown: Not Found` not very clean to user, not why it happened.

**Comment by ripcurld0** [comment] 2018-02-14 08:02
@gouyang this info was very helpful.
I could successfully reproduce the problem.

**Comment by rhatdan** [comment] 2018-02-14 10:47
@gouyang Did the default registries.conf on RHEL not have docker.io, or did you modify it?  

Are you just reporting that you think we should have a better error message to tell the user the image is not found at any of the specified registries?

**Comment by rhatdan** [comment] 2018-02-14 10:50
On Fedora I see this error when I have a bogus image

```
 buildah from foobar
no such image "foobar": image not known
```
If I remove all registies except for the redhat registry, I get the same error.
```
[registries.search]
#registries = ['docker.io', 'registry.fedoraproject.org', 'registry.access.redhat.com']
registries = ['registry.access.redhat.com']
```

**Comment by gouyang** [comment] 2018-02-14 12:09
The buildah is built from master.
```
# buildah version
Version:       0.12
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    d59af12
Built:         Wed Feb 14 06:45:04 2018
OS/Arch:       linux/amd64
```

Test on RHEL7.4, with `registries = ['registry.access.redhat.com'] ` in /etc/containers/registries.conf: 
```
# ./buildah from gouyang/foobar
unknown: Not Found
# ./buildah from busybox
unknown: Not Found
# ./buildah from foobar
unknown: Not Found
# ./buildah from gouyang/httpd
unknown: Not Found
```
with `registries = ['docker.io']` or `registries = []`:

```
# ./buildah from gouyang/httpd
Getting image source signatures
Copying blob sha256:e7bb522d92ff6d4e5b2087409b0fc783c2e3b06acf87bee739ee47d90bf02e96
^C
# ./buildah from busybox
Getting image source signatures
Copying blob sha256:57310166fe88e0dc63a80ca5c219283a932db0f3969712e2f8a86ada143bf566
^C
# ./buildah from foobar
denied: requested access to the resource is denied
unauthorized: authentication required
# ./buildah from gouyang/foobar
manifest unknown: manifest unknown
```

Please also note there is an different message for `buildah from gouyang/foobar`.

**Comment by rhatdan** [comment] 2018-02-15 15:35
@nalind @mitrmac any ideas?

**Comment by rhatdan** [comment] 2018-02-15 15:36
@runcom PTAL

**Comment by rhatdan** [comment] 2018-02-15 15:37
@mtrmac PTAL

**Comment by rhatdan** [comment] 2018-02-15 16:24
@mtrmac Any idea why we would see hugely different messages between RHEL and Fedora?

**Comment by mtrmac** [comment] 2018-02-15 16:55
> @mtrmac Any idea why we would see hugely different messages between RHEL and Fedora?

If this is referring to
```go
 buildah from foobar
no such image "foobar": image not known
```

I believe that comes from something like https://github.com/projectatomic/buildah/blob/815cedfc71fff7460b683b5f9e8fe053b31a31ef/new.go#L223 .

**Comment by ripcurld0** [comment] 2018-02-15 17:11
@mtrmac yes, that's right.
We are checking if the `errors.Cause` of the error is type of `errcode` and assumed the errorcode will contain a good error message (like in the `unauthorized` case).

Are you saying we shouldn't relay on that?

**Comment by mtrmac** [comment] 2018-02-15 17:35
I am overall a bit confused by the conversation in this bug. It shows quite a few different environments, cases and outputs, and it’s not overall clear to me what is the specific issue being solved. Is it that the human-readable error messages, i.e. the `.Error()` values, from c/image lack context? Is it something about how `buildah` is adding/not adding its own context?

Is it unknown/still changing just because no-one has looked into the code in sufficient detail yet? Or are we having distinct parallel conversations here?


> We are checking if the errors.Cause of the error is type of errcode and assumed the errorcode will contain a good error message (like in the unauthorized case).
>
> Are you saying we shouldn't relay on that?

I’m not sure that’s a good use of `errors.Cause`. The idea of `errors.Wrapf` is to _add context_ to the underlying “cause”; so, `errors.Cause` necessarily _removes context_. I’d lean towards using `errors.Cause` for _machine decisions_ (“what kind of failure is this”), where the added human-readable and non-API strings are unusable, but preserving _full text_ (not just the “cause”/”errcode” for human-readable error messages (unless the machine specifically decides using based no the `Cause` that the context is irrelevant). Or, in some cases, go all in and
```go
if errors.Cause(err) == someExpectedValue {
  report(text_entirely_independent_of_err).
}
```

**Comment by mtrmac** [comment] 2018-02-15 17:37
> I am overall a bit confused by the conversation in this bug.

Also, if every reported “bad” case of missing context could be accompanied with the `--debug` output from the same situation, that would probably be helpful in quickly tracking down the error flow.

**Comment by mtrmac** [comment] 2018-02-15 17:40
> I’m not sure that’s a good use of `errors.Cause`

To be more specific, this issue will probably be the last push for me to add at least the repo name as a context to the `unknown: not found` messages. If `buildah` then uses `errors.Cause` to strip it away, it can’t benefit. (OTOH, sure, the chain of wrapped context annotations can get horribly long, and if `buildah` know exactly what is going on, it can be quite justified in stripping it away.)

**Comment by ripcurld0** [comment] 2018-02-15 23:23
I agree with you @mtrmac 
I guess I shouldn't have stripped the error drastically.

**Comment by TomSweeneyRedHat** [comment] 2018-02-24 15:25
Closing via #485. Thanks all for the investigation on this.

**Closed** 2018-02-24 15:29 UTC
Labels: bug

**Comment by mtrmac** [comment] 2018-02-26 20:16
> To be more specific, this issue will probably be the last push for me to add at least the repo name as a context to the unknown: not found messages.

See https://github.com/containers/image/pull/420 .
