### ISSUE TITLE
`buildah run` fails with Go JSON unmarshaling error

### ISSUE THREAD

**Issue by kerscher** [projectatomic/buildah#443] opened 2018-02-02 14:26 UTC
Right after using `buildah from docker://ubuntu:16.04`, any attempt to `buildah run` inside the newly created working container fails.

## Steps to reproduce

Below `$` represents a  shell prompt:
```shell
$ container=$(buildah from docker://ubuntu:16.04)

$ printf "${container}\n"
ubuntu-working-container

$ buildah run "${container}" -- ls
json: cannot unmarshal object into Go value of type []string
```

## Versions used

```
$ apt list -a buildah
buildah/xenial,xenial,now 0.11-1~ubuntu16.04.2~ppa1 all [installed]
```
```
$ buildah version
buildah version
Version:       0.11
Go Version:    go1.9.2
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    c615c3e
Built:         Mon Jan 29 19:07:35 2018
OS/Arch:       linux/amd64
```
```
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
$ uname -a
Linux desktop 4.13.0-32-generic #35~16.04.1-Ubuntu SMP Thu Jan 25 10:13:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /etc/containers/storage.conf 
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = ""

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]
```

**Comment by rhatdan** [comment] 2018-02-02 15:42
Could this be a mismatch of the runc version?

**Comment by kerscher** [comment] 2018-02-02 16:37
This is my current `runc`:
```
runc version spec: 1.0.0-rc2-dev
```
Is there a recommended version?

**Comment by rhatdan** [comment] 2018-02-02 17:24
Yes runc 1.0.0.rc4 at least.

**Comment by rhatdan** [comment] 2018-02-02 17:24
runc --version
runc version 1.0.0-rc4+dev
spec: 1.0.0

**Comment by ripcurld0** [comment] 2018-02-04 07:02
@kerscher thank you for the report. I am closing this because this is not a bug.
Nevertheless, feel free to continue the conversation here. 👍

**Closed by ripcurld0** 2018-02-04 07:02 UTC
